/**
 * Shared types for the patS AI Safety Agent system.
 *
 * Every agent is a pure, independently-runnable function that returns a list of
 * AgentFinding objects. The Master Safety Engine composes them and the alerts store
 * persists the resulting report + a decision log.
 */

export type AgentKind = "mixing" | "allergy" | "fraud" | "dosage";

/** Clinical severity. "none" means the agent ran and found nothing actionable. */
export type Severity = "none" | "low" | "medium" | "high";

/** UI tint the surface should apply to the related card/panel. */
export type UIStatus = "ok" | "warn" | "danger";

export const SEVERITY_RANK: Record<Severity, number> = { none: 0, low: 1, medium: 2, high: 3 };

export function uiStatusForSeverity(s: Severity): UIStatus {
  if (s === "high") return "danger";
  if (s === "medium" || s === "low") return "warn";
  return "ok";
}

export interface AgentFinding {
  id: string;
  agent: AgentKind;
  severity: Severity;
  uiStatus: UIStatus;
  title: string;
  /** Plain-language explanation shown to the patient. */
  explanation: string;
  recommendation: string;
  /** Medicine names involved. */
  affectedItems: string[];
  /** Prescription codes involved (for card tinting). */
  affectedPrescriptions: string[];
  /** 0–1 confidence (fraud agent in particular). */
  confidence?: number;
  meta?: Record<string, unknown>;
}

export interface AgentResult {
  agent: AgentKind;
  ran: boolean;
  severity: Severity; // highest among findings
  uiStatus: UIStatus;
  findings: AgentFinding[];
  /** Free-form payload (e.g. dosage agent returns the generated schedule here). */
  data?: unknown;
}

/** A dose slot generated by the dosage agent. */
export interface DoseSlot {
  medication: string;
  time: string; // HH:MM (24h)
  label: string; // human label e.g. "8:00 AM"
  state: "taken" | "upcoming" | "missed" | "due";
}

export interface DosageSchedule {
  perMedication: { medication: string; frequency: string; times: string[]; durationDays?: number }[];
  today: DoseSlot[];
  adherence: number; // 0–100
}

export interface SafetyReport {
  patient: string;
  generatedAt: string;
  overallSeverity: Severity;
  overallStatus: UIStatus;
  agents: Record<AgentKind, AgentResult>;
  /** Flattened, actionable findings (severity != none), highest first. */
  findings: AgentFinding[];
  /** Notifications the patient should see (action required). */
  notifications: { severity: Severity; title: string; body: string }[];
}

/** One row appended to the immutable decision log every time the engine runs. */
export interface DecisionLogEntry {
  at: string;
  patient: string;
  trigger: string;
  agent: AgentKind | "engine";
  severity: Severity;
  summary: string;
}

/** Normalized inputs the engine assembles and passes to each agent. */
export interface ActiveMedication {
  prescriptionId: string;
  code: string;
  name: string;
  ingredients: string[];
  dosageMg?: number;
  frequency: string;
  durationDays?: number;
  doctor: string;
  date: string;
}

export interface SafetyContext {
  patient: string;
  allergies: string[];
  activeMedications: ActiveMedication[];
  /** Full prescription history (for behavioral fraud detection). */
  history: { code: string; ingredients: string[]; doctor: string; date: string }[];
  adherence: number;
  trigger: string;
}
